### ISSUE TITLE
一个瀑布流相册

### ISSUE THREAD

**Issue by naseeihity** [naseeihity/LearnToLearn#21]
前两天看到一个纯CSS方案实现类似于500px的图片瀑布流，主要特点是每行近似等高，每幅图不等宽，可以根据窗口大小自动调整每一行的图片数目。

模仿给自己的博客做了个相册，结合了之前做的图片渐进式加载和懒加载，样式还没调整，最后的效果是这样的：
![](http://7xr09v.com1.z0.glb.clouddn.com/demo_cssphoto.PNG)

核心代码也就几行，主要依赖flex布局的flex-grow属性。这里我用React进行的模板渲染，初始设置每行图片的高度为300px左右（lineHeight），拿到图片的宽度和高度后计算得到每一个图片的宽度，然后依靠flex-grow属性使得图片自动拉伸填满整行。

核心代码如下：
```css
divStyle: {
  width: width*this.state.lineHeight/height + 'px',
 flexGrow: width*this.state.lineHeight/height
},
iStyle: {
   paddingBottom: height/width * 100 + '%'
}

.img_box{
    display: flex;
    flex-wrap: wrap;
}

.img_box::after {
  content: '';
  flex-grow: 1e4;
  min-width: 20%;
}

.placeholder{
    margin: 2px;
    background-color: #ddd;
    position: relative;
    cursor: pointer;
}


.placeholder img{
    position: absolute;
    top: 0;
    width: 100%;
    vertical-align: bottom;
}
```

```js
constructor(props){
		super(props);

		this.state = {
			divStyle:{},
			iStyle:{},
			lineHeight: 300
		}
	}

	componentDidMount(){
		let img = this.props.img;
		let id = this.props.id,
			  width = img.width,
				height = img.height;

		this.setState({
			divStyle: {
				width: width*this.state.lineHeight/height + 'px',
				flexGrow: width*this.state.lineHeight/height
			},
			iStyle: {
				paddingBottom: height/width * 100 + '%'
			}
		})
	}

    render(){
		const IMG_S = "?imageView2/2/w/30/h/20/interlace/0/q/100";
		return(
			<picture className="placeholder">
				<img src={this.props.src + IMG_S}
					   alt={this.props.alt}
					   id={this.props.id}
					   className="img_small" />
				<span>{this.props.alt}</span>
			</picture>
		)
	}
```

其中，padding-bottom还是起到之前的placeholder的作用，防止图片加载过程中布局不断地重排，闪瞎眼睛。

#### 参考

1. [使用纯 CSS 实现 Google Photos 照片列表布局](https://github.com/xieranmaya/blog/issues/4)
2. [由flickr提供的js版本](https://github.com/flickr/justified-layout)
